### ISSUE TITLE
Remove Google result redirect on right click

### ISSUE THREAD

**Issue by Mte90** [matagus/remove-google-redirects-addon#13]
http://userscripts-mirror.org/scripts/show/141072

**Comment by matagus** [comment]
Hi @Mte90:

what did you mean with this link? If you meant that this addon should remove redirects on right click, well, it does indeed.

I'm going to close this issue because it seems invalid to me. If I'm wrong please tell me and I'll reopen it.

Thanks!

**Comment by Mte90** [comment]
Uhm, many months have gone and is difficult to remember the reasons for this ticket.
Now the problem not exist :-)
