### ISSUE TITLE
Middle click does not mark page as visited (link doesn't turn purple)

### ISSUE THREAD

**Issue by ivanatpr** [matagus/remove-google-redirects-addon#14]
The addon is currently preventing links from being marked as visited when middle clicking on a link in google search results in order to open that link in a new tab in the background. Ctrl-clicking on a link has the same problem. However, the issue is not present if you right-click on the link and select "open in new tab".

**Comment by matagus** [comment]
This fix will ship in version 1.4, coming soon. Thanks for reporting it!

**Comment by ivanatpr** [comment]
Awesome, thank you!
