### ISSUE TITLE
No longer work in Firefox 40.0a2

### ISSUE THREAD

**Issue by wangweij** [matagus/remove-google-redirects-addon#15]
I think it's after Firefox claims it will use separate processes for different tabs (or websites, I am not sure).

**Comment by easyaspi314** [comment]
Also reported here: [Bugzilla 1165913 - "Google Redirects Fixer" does not work with e10s](https://bugzilla.mozilla.org/show_bug.cgi?id=1165913)

**Comment by matagus** [comment]
Hi @wangweij, thanks for submitting this issue. I wasn't aware of it: I'll be working to make it work.

**Comment by matagus** [comment]
I'm submitting a new version (2.0.0) of this addon to addons.mozilla.org to be reviewed. As soon as it gets approved, it'll be available for everyone to be installed.

thanks for your help
