### ISSUE TITLE
Not compatible with firefox multiprocess

### ISSUE THREAD

**Issue by undu** [matagus/remove-google-redirects-addon#26]
I know your addon is already supposed to be compatible with e10s, but when I enable it multiprocess gets disabled.
[Mozilla's addon compatibility reporter](https://addons.mozilla.org/en-GB/firefox/addon/add-on-compatibility-reporter/?src=api) also reports the addon as multiprocess incompatible.

I'm using the latest AMO's version: 2.1.0

**Comment by matagus** [comment]
closed by #27

release in the way!
